# Generated by Django 3.2.4 on 2021-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_specproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='specproduct',
            name='analog_pins',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
