# Generated by Django 3.2.4 on 2021-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_specproduct_flash_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specproduct',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='width',
            field=models.FloatField(),
        ),
    ]
