# Generated by Django 3.2.4 on 2021-08-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210813_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specproduct',
            name='microcontroller',
            field=models.CharField(max_length=20, verbose_name="'Microcontroller'"),
        ),
    ]
