# Generated by Django 3.2.4 on 2021-08-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210813_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specproduct',
            name='IO_pins',
            field=models.IntegerField(verbose_name='I/O Pins'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='analog_pins',
            field=models.IntegerField(verbose_name='Analog Pins'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='clock_speed',
            field=models.IntegerField(verbose_name='Clock Speed'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='dc_current_for_3_3v_pin',
            field=models.IntegerField(verbose_name='DC Current for 3.3V Pin'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='dc_current_per_IO_pin',
            field=models.IntegerField(verbose_name='DC Current Per I/O Pin'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='eeprom',
            field=models.CharField(max_length=20, verbose_name='EEPROM'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='flash_memory',
            field=models.CharField(max_length=100, verbose_name='Flash Memory'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='input_voltage_limit',
            field=models.CharField(max_length=10, verbose_name='Input Voltage Limit'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='input_voltage_recomended',
            field=models.CharField(max_length=10, verbose_name='Input Voltage Recomended'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='led_builtin',
            field=models.IntegerField(verbose_name='LED BuiltIn'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='length',
            field=models.FloatField(verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='pwm_IO_pins',
            field=models.IntegerField(verbose_name='PWM I/O Pins'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='sram',
            field=models.CharField(max_length=20, verbose_name='SRAM'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='weight',
            field=models.IntegerField(verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='specproduct',
            name='width',
            field=models.FloatField(verbose_name='Width'),
        ),
    ]
